import "./globals.css";
import { Raleway } from "next/font/google";
import localfont from "next/font/local"
import { Header } from "../components/Header";

export const metadata = {
	title: "Galos Casa Creativa",
	description: "Generated by create next app",
};

const raleway = Raleway({
	subsets: ["latin"],
	variable: "--principale-font",
	weight: ["400", "500", "600", "700"],
});

const gotham = localfont({
	src: [
		{
			path: "../../public/fonts/GothamLight.ttf",
			weight: "300"
		},
		{
			path: "../../public/fonts/GothamMedium_1.ttf",
			weight: "500"
		},
		{
			path: "../../public/fonts/GothamBold.ttf",
			weight: "700"
		}
	],
	variable: "--secundary-font"
})

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${raleway.variable} ${gotham.variable} antialiased`}
		>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
