import "./globals.css";
import { Oswald, Source_Serif_4 } from "next/font/google";
import { Header } from "../components/Header";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const oswald = Oswald({
	subsets: ["latin"],
	variable: "--principal-font",
	weight: ["400", "500", "600"],
});
const source_Serif_4 = Source_Serif_4({
	subsets: ["latin"],
	variable: "--secundary-font",
	weight: ["400", "600", "700"],
});

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${oswald.variable} ${source_Serif_4.variable} antialiased`}
		>
			<body>
				{/* <Header /> */}
				{children}
			</body>
		</html>
	);
}
